name: Frontend CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        working-directory: frontend
        run: npm ci
      - name: Run Tests
        working-directory: frontend
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        working-directory: frontend
        run: npm ci
      - name: Build Frontend
        working-directory: frontend
        run: npm run build
      - name: Deploy
        run: echo "Deploying frontend..."
