name: "Lecture 1: Frontend CI"

on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - ./github/**
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        working-directory: lecture-1
        run: npm ci
      - name: Run Tests
        working-directory: lecture-1
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        working-directory: lecture-1
        run: npm ci
      - name: Build Frontend
        working-directory: lecture-1
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying frontend..."
          echo "Frontend deployed!"
